{{- if not .Values.genesis.external }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.genesis.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "lean-devnet.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.genesis.storageClass }}
  storageClassName: {{ .Values.genesis.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.genesis.storageSize }}
{{- end }}
