{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lean-devnet
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "lean-devnet.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: lean-devnet
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
{{- end }}
